Repository newrelic/nri-prometheus, pull requests merged in 2019-09, with the labels that each got.

#5 Add Travis CI
  .travis.yml
Labels: enhancement, ready-for-review

#3 Add CLA badge to README
  README.md
Labels: documentation

#6 Update to infra metrics endpoint
  internal/cmd/scraper/scraper.go
Labels: bug

#8 Add encrypted secrets to Travis CI
  .travis.yml
Labels: enhancement, ready-for-review

#9 Add Travis CI badge to the README
  README.md
Labels: documentation, ready-for-review

#17 Documentation improvements and matching with the codebase
  cmd/nri-prometheus/config.go
  deploy/nri-prometheus.tmpl.yaml
Labels: documentation, ready-for-review

#15 Add support for summaries and histograms
  README.md
  cmd/nri-prometheus/config.go
  internal/cmd/scraper/scraper.go
  internal/histogram/bucket.go
  internal/histogram/percentile.go
  internal/histogram/percentile_test.go
  internal/integration/emitter.go
  internal/integration/emitter_test.go
  internal/integration/fetcher.go
  internal/integration/fetcher_test.go
Labels: enhancement, ready-for-review
